- hosts: "{{ nodes }}"
  remote_user: itadmin
  become: yes
  connection: paramiko
  vars_files:
    - v1.yml
  tasks:
    - name: add user test1
      user:
        name: test1
        home: /var/lib/test1
        shell: /bin/bash
        uid: 1101
        group: test1
      tags: add_user_test1
        
    - name: add user test2
      user:
        name: test2
        home: /var/lib/test2
        shell: /sbin/nologin
        uid: 1102
        group: test2
      tags: add_user_test2
