- hosts: "{{ nodes }}"
  remote_user: itadmin
  become: yes
  connection: paramiko
  vars_files:
    - v1.yml
  tasks:
    - name: file copy
      copy:
        src: files/junkcopy
        dest: /opt/file_backup_dir/junk1
      tags: file_copy
