- hosts: "{{ nodes }}"
  remote_user: itadmin
  become: yes
  connection: paramiko
  vars_files:
    - v1.yml
  tasks:
    - name: fetch file from remote node
      fetch:
        src: /opt/file_backup_dir/fetchfilefromg2
        dest: /etc/ansible/files/
        flat: yes
      tags: fetch_file_from_remote_node
