- hosts: "{{ nodes }}"
  remote_user: itadmin
  become: yes
  connection: paramiko
  vars_files:
    - v1.yml
  tasks:
    - name: folder permission ownership change
      file:
        path: /opt/file_backup_dir/junk1
        state: directory
        owner: test1
        group: test1
        recurse: yes
        mode: '0644'
      tags: folder_permission_ownership_change
