- hosts: "{{ nodes }}"
  remote_user: itadmin
  become: yes
  connection: paramiko
  vars_files:
    - v1.yml
  tasks:
    - name: folder permission adjustment
      file:
        path: /opt/file_backup_dir/test
        state: directory
        mode: '0755'
      tags: folder_permission_adjustment
