- hosts: "{{ nodes }}"
  connection: paramiko
  remote_user: itadmin
  become: yes
  vars_files: 
    - v1.yml
 
  tasks:
    - name: hostname display
      shell: hostname
      register: result

    - debug:
        msg: "{{ result.stdout_lines }}"
