- hosts: "{{ nodes }}"
  remote_user: itadmin
  become: yes
  connection: paramiko
  vars_files:
    - v1.yml
  tasks:
    - name: info search
      include_role:
        name: "{{ item }}"
      with_items:
        - InfoSearch_Role
