- hosts: "{{ nodes }}"
  remote_user: itadmin
  become: yes
  connection: paramiko
  vars_files:
    - v1.yml
  tasks:
    - name: replace line 2 with item 2
      lineinfile:
        path: /opt/file_backup_dir/test031921
        regexp: 'line2'
        line: 'item2'
      tags: replace_line2_with_item2
